import {StyleSheet} from 'react-native';
import {Color} from '../assets/Utils/Colors';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from '../assets/Responsive_Dimensions';

export const styles = StyleSheet.create({
  welcomeTextStyle: {
    color: Color.white,
    fontSize: responsiveFontSize(3.8),
  },
  inputStyle: {
    borderColor: Color.white,
    alignItems: 'center',
    borderWidth: 2,
    borderRadius: responsiveHeight(3.5),
    width: responsiveWidth(85),
    padding: responsiveHeight(2),
    height: responsiveHeight(6.5),
  },
  listingCard: {
    padding: responsiveHeight(2),
    width: '100%',
    backgroundColor: Color.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 8,
    borderRadius: 8,
    borderBottomRightRadius: 0,
  },

  locationContainer: {
    height: responsiveHeight(7.5),
    paddingHorizontal: responsiveWidth(4),
    backgroundColor: Color.themeColor,
    alignItems: 'center',
    borderTopLeftRadius: responsiveHeight(2),
    borderTopRightRadius: responsiveHeight(2.2),
    borderBottomRightRadius: responsiveHeight(2.5),
    borderBottomLeftRadius: 0,
  },
  iconTxtContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: responsiveHeight(1.5),
  },

  postImage: {
    height: responsiveHeight(25),
    width: '100%',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },

  goContainer: {
    paddingHorizontal: responsiveWidth(3.5),
    backgroundColor: Color.themeColor,
    alignItems: 'center',
    height: responsiveHeight(5.4),
    justifyContent: 'center',
    alignItems: 'center',
    borderTopLeftRadius: responsiveHeight(2),
    borderTopRightRadius: responsiveHeight(2.1),
    borderBottomRightRadius: responsiveHeight(2.1),
    borderBottomLeftRadius: 0,
  },
  profileHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: responsiveHeight(1.5),
    paddingHorizontal: responsiveWidth(5),
    backgroundColor: Color.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    borderWidth: 1,
    borderColor: Color.postBorderColor,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginBottom: 20,
  },
  actionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: responsiveHeight(2),
  },
  captionText: {
    padding: 15,
    paddingBottom: 20,
    color: Color.black,
    fontSize: responsiveFontSize(1.7),
  },
  postContainer: {
    paddingHorizontal: responsiveWidth(5.7),
    paddingVertical: responsiveHeight(2.5),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    borderWidth: 1,
    borderColor: Color.postBorderColor,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    backgroundColor: Color.white,
    elevation: 3,
    marginBottom: responsiveHeight(3),
  },
  captionPostCotainer: {
    borderWidth: 1,
    borderColor: Color.themeColor,
    borderBottomWidth: null,
    borderTopLeftRadius: 3,
    borderTopRightRadius: 5,
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    marginTop: responsiveHeight(2),
  },
  timeContainer: {
    height: '100%',
    paddingHorizontal: responsiveWidth(3),
    backgroundColor: Color.themeColor,
    alignItems: 'center',
    borderTopLeftRadius: responsiveHeight(2),
    borderTopRightRadius: responsiveHeight(2.2),
    borderBottomRightRadius: responsiveHeight(2.5),
    borderBottomLeftRadius: 0,
  },
  timeContainer2: {
    height: '100%',
    paddingHorizontal: responsiveWidth(3.5),
    backgroundColor: Color.themeColor,
    alignItems: 'center',
    borderTopLeftRadius: responsiveHeight(2),
    borderTopRightRadius: responsiveHeight(2.1),
    borderBottomRightRadius: responsiveHeight(2.1),
    borderBottomLeftRadius: 0,
  },
  listingText: {
    color: Color.textLight,
    fontSize: responsiveFontSize(1.5),
    marginTop: responsiveHeight(0.7),
    width: responsiveWidth(33),
  },
  listingSemiHeading: {
    color: Color.black,
    fontSize: responsiveFontSize(1.8),
    fontWeight: '400',
  },
  detailsHeading: {
    color: Color.themeColor,
    fontSize: responsiveFontSize(1.7),
    fontWeight: '500',
  },
  parentContainer: {
    flex: 1,
    backgroundColor: Color.white,
  },
  parentScrollContainer: {
    flexGrow: 1,
    backgroundColor: Color.white,
  },
  detailsText: {
    color: Color.textDark,
    fontSize: responsiveFontSize(1.7),
  },
  searchInputContainer: {
    position: 'absolute',
    marginTop: responsiveHeight(4),
    // zIndex: 10,
    flexDirection: 'row',
    gap: responsiveHeight(1.5),
    alignSelf: 'center',
  },
  inputContainer: {
    backgroundColor: Color.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    borderWidth: 1,
    borderColor: Color.postBorderColor,
    borderRadius: responsiveHeight(1.3),
    borderBottomRightRadius: 0,
  },

  input: {
    height: responsiveHeight(6),
    width: responsiveWidth(70),
    paddingHorizontal: responsiveHeight(2),
    zIndex: 10,
    color: Color.black,
  },
  headerIconStyle: {
    borderWidth: 1,
    backgroundColor: Color.white,
    borderColor: Color.themeColor,
    borderRadius: responsiveHeight(3.4),
    width: responsiveWidth(9.4),
    height: responsiveHeight(4.3),
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeHolderStyle1: {
    color: Color.placeHolderTxt1,
    fontSize: responsiveFontSize(1.8),
  },
  placeHolderStyle2: {
    color: Color.black,
    fontSize: responsiveFontSize(1.8),
    fontWeight: '500',
  },
  orText: {
    color: Color.placeHolderTxt1,
    alignSelf: 'center',
    fontSize: responsiveFontSize(2),
    marginVertical: responsiveHeight(3),
  },
  btnStyle: {
    backgroundColor: Color.themeColor,
    borderRadius: responsiveHeight(3.5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnTxt: {
    color: Color.white,
    textAlign: 'center',
    fontSize: responsiveFontSize(1.9),
  },
  socialButtonStyle: {
    width: responsiveWidth(85),
    borderRadius: responsiveHeight(3.3),
    gap: responsiveHeight(3),
    paddingHorizontal: 20,
    borderColor: Color.white,
    borderWidth: 2,
    height: responsiveHeight(7),
    flexDirection: 'row',
    alignItems: 'center',
  },
  socialBtnText: {
    color: Color.white,
    fontSize: responsiveFontSize(1.9),
  },
});
